# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SerialToolUI.ui'
#
# Created: Wed Jun 06 12:55:46 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!
# -*- coding: utf-8 -*-
from PyQt4 import QtCore
from PyQt4 import QtGui
from PyQt4.QtGui import *
from PyQt4.QtCore import *
import sys
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Espressif(QtGui.QWidget):
    def setupUi(self, Espressif):
        Espressif.setObjectName(_fromUtf8("Espressif"))
        Espressif.resize(865, 768)
        self.portchoose_t = QtGui.QLabel(Espressif)
        
        palette1 = QtGui.QPalette(self)
        #palette1.setColor(self.backgroundRole(), QColor(192,253,123))   # 设置背景颜色
        palette1.setBrush(self.backgroundRole(), QtGui.QBrush(QtGui.QPixmap('./image/BackGround.PNG')))   # 设置背景图片
        self.setPalette(palette1)        
        
        self.portchoose_t.setGeometry(QtCore.QRect(20, 50, 72, 15))
        self.setWindowIcon(QIcon('./image/espressif.png'))
        self.portchoose_t.setObjectName(_fromUtf8("portchoose_t"))
        self.baudratelchoose = QtGui.QComboBox(Espressif)
        self.baudratelchoose.setEnabled(True)
        self.baudratelchoose.setGeometry(QtCore.QRect(90, 90, 91, 21))
        self.baudratelchoose.setObjectName(_fromUtf8("baudratelchoose"))
        self.baudratelchoose.addItem(_fromUtf8(""))
        self.baudratelchoose.addItem(_fromUtf8(""))
        self.baudratelchoose.addItem(_fromUtf8(""))
        self.baudratelchoose.addItem(_fromUtf8(""))
        self.comchoose = QtGui.QComboBox(Espressif)
        self.comchoose.setGeometry(QtCore.QRect(90, 50, 91, 21))
        self.comchoose.setObjectName(_fromUtf8("comchoose"))
        self.comchoose.addItem(_fromUtf8(""))
        self.baundrate_t = QtGui.QLabel(Espressif)
        self.baundrate_t.setGeometry(QtCore.QRect(20, 90, 72, 15))
        self.baundrate_t.setObjectName(_fromUtf8("baundrate_t"))
        self.stop_t = QtGui.QLabel(Espressif)
        self.stop_t.setGeometry(QtCore.QRect(20, 130, 72, 15))
        self.stop_t.setObjectName(_fromUtf8("stop_t"))
        self.stopChoose = QtGui.QComboBox(Espressif)
        self.stopChoose.setGeometry(QtCore.QRect(90, 130, 87, 22))
        self.stopChoose.setObjectName(_fromUtf8("stopChoose"))
        self.stopChoose.addItem(_fromUtf8(""))
        self.stopChoose.addItem(_fromUtf8(""))
        self.stopChoose.addItem(_fromUtf8(""))
        self.data_t = QtGui.QLabel(Espressif)
        self.data_t.setGeometry(QtCore.QRect(20, 180, 72, 15))
        self.data_t.setObjectName(_fromUtf8("data_t"))
        self.datachoose = QtGui.QComboBox(Espressif)
        self.datachoose.setGeometry(QtCore.QRect(90, 180, 87, 22))
        self.datachoose.setObjectName(_fromUtf8("datachoose"))
        self.datachoose.addItem(_fromUtf8(""))
        self.datachoose.addItem(_fromUtf8(""))
        self.datachoose.addItem(_fromUtf8(""))
        self.datachoose.addItem(_fromUtf8(""))
        self.check_t = QtGui.QLabel(Espressif)
        self.check_t.setGeometry(QtCore.QRect(10, 230, 72, 15))
        self.check_t.setObjectName(_fromUtf8("check_t"))
        self.checkchoose = QtGui.QComboBox(Espressif)
        self.checkchoose.setGeometry(QtCore.QRect(90, 230, 87, 22))
        self.checkchoose.setObjectName(_fromUtf8("checkchoose"))
        self.checkchoose.addItem(_fromUtf8(""))
        self.checkchoose.addItem(_fromUtf8(""))
        self.checkchoose.addItem(_fromUtf8(""))
        self.portopet_t = QtGui.QLabel(Espressif)
        self.portopet_t.setGeometry(QtCore.QRect(10, 280, 72, 15))
        self.portopet_t.setObjectName(_fromUtf8("portopet_t"))
        self.portoperate = QtGui.QPushButton(Espressif)
        self.portoperate.setGeometry(QtCore.QRect(90, 270, 93, 28))
        self.portoperate.setObjectName(_fromUtf8("portoperate"))
        self.saveInfo = QtGui.QPushButton(Espressif)
        self.saveInfo.setGeometry(QtCore.QRect(10, 330, 93, 28))
        self.saveInfo.setObjectName(_fromUtf8("saveInfo"))
        self.clearInfo = QtGui.QPushButton(Espressif)
        self.clearInfo.setGeometry(QtCore.QRect(120, 330, 93, 28))
        self.clearInfo.setObjectName(_fromUtf8("clearInfo"))
        self.Time = QtGui.QCheckBox(Espressif)
        self.Time.setGeometry(QtCore.QRect(10, 380, 91, 19))
        self.Time.setObjectName(_fromUtf8("Time"))
        self.InfoBrower = QtGui.QTextBrowser(Espressif)
        self.InfoBrower.setGeometry(QtCore.QRect(240, 50, 621, 381))
        self.InfoBrower.setObjectName(_fromUtf8("InfoBrower"))
        self.TabWidget = QtGui.QTabWidget(Espressif)
        self.TabWidget.setGeometry(QtCore.QRect(10, 460, 851, 291))
        self.TabWidget.setObjectName(_fromUtf8("TabWidget"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.inFoSend = QtGui.QPushButton(self.tab_3)
        self.inFoSend.setGeometry(QtCore.QRect(730, 20, 93, 28))
        self.inFoSend.setObjectName(_fromUtf8("inFoSend"))
        self.InfoClear = QtGui.QPushButton(self.tab_3)
        self.InfoClear.setGeometry(QtCore.QRect(730, 110, 93, 28))
        self.InfoClear.setObjectName(_fromUtf8("InfoClear"))
        self.SendNewLine = QtGui.QCheckBox(self.tab_3)
        self.SendNewLine.setGeometry(QtCore.QRect(730, 210, 91, 19))
        self.SendNewLine.setObjectName(_fromUtf8("SendNewLine"))
        self.lineEditCommand = QtGui.QLineEdit(self.tab_3)
        self.lineEditCommand.setGeometry(QtCore.QRect(0, 0, 721, 261))
        self.lineEditCommand.setObjectName(_fromUtf8("lineEditCommand"))
        self.TabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.checkSend1 = QtGui.QCheckBox(self.tab_4)
        self.checkSend1.setGeometry(QtCore.QRect(10, 30, 91, 19))
        self.checkSend1.setText(_fromUtf8(""))
        self.checkSend1.setObjectName(_fromUtf8("checkSend1"))
        self.checkSend2 = QtGui.QCheckBox(self.tab_4)
        self.checkSend2.setGeometry(QtCore.QRect(10, 70, 91, 19))
        self.checkSend2.setText(_fromUtf8(""))
        self.checkSend2.setObjectName(_fromUtf8("checkSend2"))
        self.checkSend3 = QtGui.QCheckBox(self.tab_4)
        self.checkSend3.setGeometry(QtCore.QRect(10, 110, 91, 19))
        self.checkSend3.setText(_fromUtf8(""))
        self.checkSend3.setObjectName(_fromUtf8("checkSend3"))
        self.checkSend4 = QtGui.QCheckBox(self.tab_4)
        self.checkSend4.setGeometry(QtCore.QRect(10, 150, 91, 19))
        self.checkSend4.setText(_fromUtf8(""))
        self.checkSend4.setObjectName(_fromUtf8("checkSend4"))
        self.checkSend5 = QtGui.QCheckBox(self.tab_4)
        self.checkSend5.setGeometry(QtCore.QRect(10, 190, 91, 19))
        self.checkSend5.setText(_fromUtf8(""))
        self.checkSend5.setObjectName(_fromUtf8("checkSend5"))
        self.checkSend6 = QtGui.QCheckBox(self.tab_4)
        self.checkSend6.setGeometry(QtCore.QRect(10, 230, 91, 19))
        self.checkSend6.setText(_fromUtf8(""))
        self.checkSend6.setObjectName(_fromUtf8("checkSend6"))
        self.lineEditCommand1 = QtGui.QLineEdit(self.tab_4)
        self.lineEditCommand1.setGeometry(QtCore.QRect(40, 30, 641, 21))
        self.lineEditCommand1.setObjectName(_fromUtf8("lineEditCommand1"))
        self.lineEditCommand2 = QtGui.QLineEdit(self.tab_4)
        self.lineEditCommand2.setGeometry(QtCore.QRect(40, 70, 641, 21))
        self.lineEditCommand2.setObjectName(_fromUtf8("lineEditCommand2"))
        self.lineEditCommand3 = QtGui.QLineEdit(self.tab_4)
        self.lineEditCommand3.setGeometry(QtCore.QRect(40, 110, 641, 21))
        self.lineEditCommand3.setObjectName(_fromUtf8("lineEditCommand3"))
        self.lineEditCommand4 = QtGui.QLineEdit(self.tab_4)
        self.lineEditCommand4.setGeometry(QtCore.QRect(40, 150, 641, 21))
        self.lineEditCommand4.setObjectName(_fromUtf8("lineEditCommand4"))
        self.lineEditCommand5 = QtGui.QLineEdit(self.tab_4)
        self.lineEditCommand5.setGeometry(QtCore.QRect(40, 190, 641, 21))
        self.lineEditCommand5.setObjectName(_fromUtf8("lineEditCommand5"))
        self.lineEditCommand6 = QtGui.QLineEdit(self.tab_4)
        self.lineEditCommand6.setGeometry(QtCore.QRect(40, 230, 641, 21))
        self.lineEditCommand6.setObjectName(_fromUtf8("lineEditCommand6"))
        self.inFoSend_M = QtGui.QPushButton(self.tab_4)
        self.inFoSend_M.setGeometry(QtCore.QRect(720, 30, 93, 28))
        self.inFoSend_M.setObjectName(_fromUtf8("inFoSend_M"))
        self.InFoClear_M = QtGui.QPushButton(self.tab_4)
        self.InFoClear_M.setGeometry(QtCore.QRect(720, 120, 93, 28))
        self.InFoClear_M.setObjectName(_fromUtf8("InFoClear_M"))
        self.SendNewLine_M = QtGui.QCheckBox(self.tab_4)
        self.SendNewLine_M.setGeometry(QtCore.QRect(720, 210, 91, 19))
        self.SendNewLine_M.setObjectName(_fromUtf8("SendNewLine_M"))
        self.TabWidget.addTab(self.tab_4, _fromUtf8(""))

        self.retranslateUi(Espressif)
        self.TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Espressif)

    def retranslateUi(self, Espressif):
        Espressif.setWindowTitle(_translate("Espressif", "Form", None))
        self.portchoose_t.setText(_translate("Espressif", "串口选择", None))
        self.baudratelchoose.setItemText(0, _translate("Espressif", "921600", None))
        self.baudratelchoose.setItemText(1, _translate("Espressif", "115200", None))
        self.baudratelchoose.setItemText(2, _translate("Espressif", "74880", None))
        self.baudratelchoose.setItemText(3, _translate("Espressif", "Custom", None))
        self.comchoose.setItemText(0, _translate("Espressif", "   ---", None))
        self.baundrate_t.setText(_translate("Espressif", "波特率", None))
        self.stop_t.setText(_translate("Espressif", "停止位", None))
        self.stopChoose.setItemText(0, _translate("Espressif", "1", None))
        self.stopChoose.setItemText(1, _translate("Espressif", "1.5", None))
        self.stopChoose.setItemText(2, _translate("Espressif", "2", None))
        self.data_t.setText(_translate("Espressif", "数据位", None))
        self.datachoose.setItemText(0, _translate("Espressif", "8", None))
        self.datachoose.setItemText(1, _translate("Espressif", "7", None))
        self.datachoose.setItemText(2, _translate("Espressif", "6", None))
        self.datachoose.setItemText(3, _translate("Espressif", "5", None))
        self.check_t.setText(_translate("Espressif", "奇偶校验", None))
        self.checkchoose.setItemText(0, _translate("Espressif", "无", None))
        self.checkchoose.setItemText(1, _translate("Espressif", "奇校验", None))
        self.checkchoose.setItemText(2, _translate("Espressif", "偶校验", None))
        self.portopet_t.setText(_translate("Espressif", "串口操作", None))
        self.portoperate.setText(_translate("Espressif", "close", None))
        self.saveInfo.setText(_translate("Espressif", "保存窗口", None))
        self.clearInfo.setText(_translate("Espressif", "清除窗口", None))
        self.Time.setText(_translate("Espressif", "时间撮", None))
        self.inFoSend.setText(_translate("Espressif", "发送", None))
        self.InfoClear.setText(_translate("Espressif", "清除发送", None))
        self.SendNewLine.setText(_translate("Espressif", "发送新行", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab_3), _translate("Espressif", "单行发送", None))
        self.inFoSend_M.setText(_translate("Espressif", "发送", None))
        self.InFoClear_M.setText(_translate("Espressif", "清除发送", None))
        self.SendNewLine_M.setText(_translate("Espressif", "发送新行", None))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.tab_4), _translate("Espressif", "多行发送", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Espressif = QtGui.QWidget()
    ui = Ui_Espressif()
    ui.setupUi(Espressif)
    Espressif.show()
    sys.exit(app.exec_())

